apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tzfd0cwcs-dotnet-basic
  janus-idp.io/tekton: tzfd0cwcs-dotnet-basic
  backstage.io/kubernetes-id: tzfd0cwcs-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tzfd0cwcs-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
